# Change these first
owner: ArvorInsurance
repo: system_health

# Add necessary permissions and settings
assignees: []
autoAssign: false
autoClose: false
branches: [master]
commitMessagePrefix: ""
labels: []
repository: ArvorInsurance/system_health
timezone: America/New_York

# Force Upptime to create commits even when status doesn't change
forceCommit: true
commitInterval: 300
alwaysCommit: true
skipCommit: false

sites:
  - name: Company Research Website
    url: https://company-research.apps.arvorinsurance.com/
  - name: Advice App
    url: https://advice-pane.apps.arvorinsurance.com/
  - name: Submissions Health
    url: https://submissions.apps.arvorinsurance.com/api/health

status-website:
  baseUrl: /system_health
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Arvor Insurance Status
  introTitle: "Arvor Insurance System Health"
  introMessage: "This status page shows real-time uptime data for our services."
  navbar:
    - title: Status
      href: /system_health/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
