# Change these first
owner: ArvorInsurance
repo: system_health

# Add necessary permissions and settings
assignees: []
autoAssign: false
autoClose: false
branches: [master]
commitMessagePrefix: ""
labels: []
repository: ArvorInsurance/system_health
timezone: America/New_York

# Force commits every 5 minutes even when status doesn't change
forceCommit: true
commitInterval: 300

sites:
  - name: Company Research Website
    url: https://company-research.apps.arvorinsurance.com/
  - name: Company Research Health
    url: https://company-research.apps.arvorinsurance.com/api/health
  - name: Company Research Auth
    url: https://company-research.apps.arvorinsurance.com/api/auth/verify
  - name: Company Research Core API
    url: https://company-research.apps.arvorinsurance.com/api/advice/research

status-website:
  baseUrl: /system_health
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Arvor Insurance Status
  introTitle: "Arvor Insurance System Health"
  introMessage: "This status page shows real-time uptime data for our services."
  navbar:
    - title: Status
      href: /system_health/     # ← 改成帶 baseUrl 的路徑
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
